export const TURISTICKA_AGENCIJA_URL = 'http://localhost:8083/TuristickaAgencija'
export const DESTINACIJA_URL = 'http://localhost:8083/Destinacija'
export const HOTEL_URL = 'http://localhost:8083/Hotel'
export const ARANZMAN_URL = 'http://localhost:8083/Aranzman'
export const ARANZMAN_AGENCIJA_URL = 'http://localhost:8083/Aranzman/TuristickaAgencija'